# Generated by Django 5.2.8 on 2025-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه کاربر'),
        ),
    ]
