# Generated by Django 5.2.8 on 2026-01-28 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=500, verbose_name='نام وظیفه')),
                ('task_desc', models.TextField(verbose_name='توضیحات وظایف')),
                ('task_started_at', models.DateTimeField(editable=False, null=True, verbose_name='تاریخ شروع وظیفه')),
                ('task_ended_at', models.DateTimeField(null=True, verbose_name='تاریخ پایان وظیفه')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده/نشده')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
