# Generated by Django 5.2.8 on 2026-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان وظیفه'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ شروع وظیفه'),
        ),
    ]
